name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      run: echo "$SSH_PRIVATE_KEY" > ssh_key && chmod 600 ssh_key

    - name: Deploy to EC2
      run: |
        ssh -i ssh_key $SSH_USER_NAME@$SSH_IP "cd deploy && touch deploy.txt"
