name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP  }}
          username: ${{ secrets.SSH_USER_NAME  }}
          key: ${{ secrets.SSH_PRIVATE_KEY  }}
          script_stop: true
          script: |
            cd /home/ubuntu/deploy
            git checkout .
            git pull origin master
